### ISSUE TITLE
on Android 

### ISSUE THREAD

**Issue by Endistic** [fabienrousseau/flutter_pcsc#3]
hi, I have a question.
flutter_pcsc can implement on Android device ?

**Comment by fabienrousseau** [comment]
Yes it has been used successfully on Android

**Comment by Endistic** [comment]
But I found  error  establishcontext() has not been implemented. 
use device tablet ( USB TYPE-C )
smartcard reader : SCR3310 V2.0 

Can you help me about connect to devices or guildline? 
Thank you

**Comment by gkres** [comment]
> Yes it has been used successfully on Android

Can you point me in the right direction? I've been trying to read a smart card using different packages on Android for a while now with no luck.

**Comment by tjeffree** [comment]
@fabienrousseau sorry to dredge up an old thread. Was this package really used on Android? There's no Android platform code, right? Feel like I'm missing a piece of the puzzle here.
